import React, { useEffect, useRef, useState } from "react";
import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import TopBar from "@/components/TopBar";
import Welcome from "@/components/Welcome";
import About from "@/components/About";
import Services from "@/components/Services";
import data from "@/data/data";
import MyProjects from "@/components/MyProjects";
import Stories from "@/components/Stories";
import GetInTouch from "@/components/GetInTouch";
import Footer from "@/components/Footer";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  const navRef = useRef({});

  const heightRef = useRef(null);
  const handleClick = (el) => {
    navRef.current[el].scrollIntoView({ behavior: "smooth" });
  };
  const [active, setActive] = useState([]);

  let vHeight;
  useEffect(() => {
    const hash = window.location.hash;
    vHeight = window.innerHeight;
    const targetId = hash.substring(1); // Remove the leading '#' character

    if (targetId) {
      // targetDiv.scrollIntoView({ behavior: "smooth" });
      handleClick(targetId);
    }
    history.replaceState(null, null, window.location.pathname);
  }, []);

  const handleScroll = () => {
    let foundActive = true;
    Object.values(navRef.current)
      .reverse()
      .forEach((box, i) => {
        const { y } = box.getClientRects()[0];
        if (y < vHeight / 2 && foundActive) {
          foundActive = false;
          setActive(Object.keys(navRef.current).reverse()[i]);
        }
      });
  };
  useEffect(() => {
    handleScroll();
    window.addEventListener("scroll", handleScroll);
    return () => {
      console.log("cleaned");
      window.removeEventListener("scroll", handleScroll);
    };
  }, []);

  return (
    <>
      <Head>
        <title>Gio's portfolio</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon1.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
        <link
          href="https://fonts.googleapis.com/css2?family=DM+Sans:ital,wght@0,400;0,500;0,600;0,700;1,400&family=Poppins&family=Sacramento&family=Inter&display=swap"
          rel="stylesheet"
        />
      </Head>

      <main className={styles.main} style={{ position: "relative" }}>
        {/* <div style={{position:"absolute", height:"100vh", width:"100vw"}} ref={heightRef}></div> */}
        <TopBar
          handleClick={handleClick}
          topBarNav={data.topBarNav}
          active={active}
        />
        <div ref={(el) => (navRef.current.Home = el)}>
          <Welcome handleClick={handleClick} />
        </div>

        <div ref={(el) => (navRef.current.Services = el)}></div>
        <Services services={data.services} />
        <div ref={(el) => (navRef.current.Projects = el)}>
          <MyProjects projects={data.MyProjects} />
        </div>
        <div ref={(el) => (navRef.current.Testimonials = el)}>
          <Stories stories={data.successStories} />
        </div>
        <div ref={(el) => (navRef.current.About = el)}>
          <About handleClick={handleClick} />
        </div>
        <div ref={(el) => (navRef.current.GetInTouch = el)}>
          <GetInTouch />
        </div>
        <Footer navigation={data.footerBarNav} handleClick={handleClick} />
      </main>
      {/* <main className={styles.main}>
        <div className={styles.description}>
          <p>
            Get started by editing&nbsp;
            <code className={styles.code}>src/pages/index.js</code>
          </p>
          <div>
            <a
              href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
              target="_blank"
              rel="noopener noreferrer">
              By{" "}
              <Image
                src="/vercel.svg"
                alt="Vercel Logo"
                className={styles.vercelLogo}
                width={100}
                height={24}
                priority
              />
            </a>
          </div>
        </div>

        <div className={styles.center}>
          <Image
            className={styles.logo}
            src="/next.svg"
            alt="Next.js Logo"
            width={180}
            height={37}
            priority
          />
          <div className={styles.thirteen}>
            <Image
              src="/thirteen.svg"
              alt="13"
              width={40}
              height={31}
              priority
            />
          </div>
        </div>

        <div className={styles.grid}>
          <a
            href="https://nextjs.org/docs?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer">
            <h2 className={inter.className}>
              Docs <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Find in-depth information about Next.js features and&nbsp;API.
            </p>
          </a>

          <a
            href="https://nextjs.org/learn?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer">
            <h2 className={inter.className}>
              Learn <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Learn about Next.js in an interactive course with&nbsp;quizzes!
            </p>
          </a>

          <a
            href="https://vercel.com/templates?framework=next.js&utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer">
            <h2 className={inter.className}>
              Templates <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Discover and deploy boilerplate example Next.js&nbsp;projects.
            </p>
          </a>

          <a
            href="https://vercel.com/new?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
            className={styles.card}
            target="_blank"
            rel="noopener noreferrer">
            <h2 className={inter.className}>
              Deploy <span>-&gt;</span>
            </h2>
            <p className={inter.className}>
              Instantly deploy your Next.js site to a shareable URL
              with&nbsp;Vercel.
            </p>
          </a>
        </div>
      </main> */}
    </>
  );
}
